excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://katelifelived.github.io
title: Stuff about things
email: katelynarobertson@gmail.com
author: Katelyn
description: My awesome new site
paginate: 3
google_analytics: 